// SYNC
export const RESET_ACTIVE_GAME = 'RESET_ACTIVE_GAME';

// ASYNC
export const FETCH_ALL_GAMES_IN_DB_REQUESTED = 'FETCH_ALL_GAMES_IN_DB_REQUESTED';
export const FETCH_ALL_GAMES_IN_DB_SUCCEEDED = 'FETCH_ALL_GAMES_IN_DB_SUCCEEDED';
export const FETCH_ALL_GAMES_IN_DB_FAILED = 'FETCH_ALL_GAMES_IN_DB_FAILED';

export const FIND_POPULAR_GAMES_REQUESTED = 'FIND_POPULAR_GAMES_REQUESTED';
export const FIND_POPULAR_GAMES_SUCCEEDED = 'FIND_POPULAR_GAMES_SUCCEEDED';
export const FIND_POPULAR_GAMES_FAILED = 'FIND_POPULAR_GAMES_FAILED';

export const GENERATE_AUTO_SUGGESTIONS_REQUESTED = 'GENERATE_AUTO_SUGGESTIONS_REQUESTED';
export const GENERATE_AUTO_SUGGESTIONS_SUCCEEDED = 'GENERATE_AUTO_SUGGESTIONS_SUCCEEDED';
export const GENERATE_AUTO_SUGGESTIONS_FAILED = 'GENERATE_AUTO_SUGGESTIONS_FAILED';

export const SEARCH_BY_TITLE_REQUESTED = 'SEARCH_BY_TITLE_REQUESTED';
export const SEARCH_BY_TITLE_SUCCEEDED = 'SEARCH_BY_TITLE_SUCCEEDED';
export const SEARCH_BY_TITLE_FAILED = 'SEARCH_BY_TITLE_FAILED';

export const MAKE_ACTIVE_GAME_REQUESTED = 'MAKE_ACTIVE_GAME_REQUESTED';
export const MAKE_ACTIVE_GAME_SUCCEEDED = 'MAKE_ACTIVE_GAME_SUCCEEDED';
export const MAKE_ACTIVE_GAME_FAILED = 'MAKE_ACTIVE_GAME_FAILED';

export const SUBMIT_PRICE_ALERT_REQUESTED = 'SUBMIT_PRICE_ALERT_REQUESTED';
export const SUBMIT_PRICE_ALERT_SUCCEEDED = 'SUBMIT_PRICE_ALERT_SUCCEEDED';
export const SUBMIT_PRICE_ALERT_FAILED = 'SUBMIT_PRICE_ALERT_FAILED';

export const FETCH_PRICE_ALERT_REQUESTED = 'FETCH_PRICE_ALERT_REQUESTED';
export const FETCH_PRICE_ALERT_SUCCEEDED = 'FETCH_PRICE_ALERT_SUCCEEDED';
export const FETCH_PRICE_ALERT_FAILED = 'FETCH_PRICE_ALERT_FAILED'

export const DELETE_PRICE_ALERT_REQUESTED = 'DELETE_PRICE_ALERT_REQUESTED';
export const DELETE_PRICE_ALERT_SUCCEEDED = 'DELETE_PRICE_ALERT_SUCCEEDED';
export const DELETE_PRICE_ALERT_FAILED = 'DELETE_PRICE_ALERT_FAILED';

export const CHECK_BLACKLIST_REQUESTED = 'CHECK_BLACKLIST_REQUESTED';
export const CHECK_BLACKLIST_SUCCEEDED = 'CHECK_BLACKLIST_SUCCEEDED';
export const CHECK_BLACKLIST_FAILED = 'CHECK_BLACKLIST_FAILED';

export const ADD_TO_BLACKLIST_REQUESTED = 'ADD_TO_BLACKLIST_REQUESTED';
export const ADD_TO_BLACKLIST_SUCCEEDED = 'ADD_TO_BLACKLIST_SUCCEEDED';
export const ADD_TO_BLACKLIST_FAILED = 'ADD_TO_BLACKLIST_FAILED';

export const SEARCH_VIDEO_REQUESTED = 'SEARCH_VIDEO_REQUESTED';
export const SEARCH_VIDEO_SUCCEEDED = 'SEARCH_VIDEO_SUCCEEDED';
export const SEARCH_VIDEO_FAILED = 'SEARCH_VIDEO_FAILED';
